golangci lint를 템플릿화해서 제공해요!
daangn/.github pull request #4
Opened 2022-02-08 17:53 UTC by jinwoo1225

2022-02-09 00:59 UTC, isbang commented
고수준의 lint 를 사용할 수 있게 되는 것은 좋지만, default config가 이 레포지토리에 묶여있는 것은 좋아보이지 않아요. 혹시 default config를 각 레포에서 가져갈 수 있게 하기 좋은 방법이 따로 없을까요?

2022-02-09 00:59 UTC, isbang reviewed
일단은 comment 상태로 둘게요~

2022-02-09 02:00 UTC, proost requested changes
저도 default-config가 여기에 있는 것은 별로 좋아보이지 않네요. 따로 빼서 관리하는 게 맞지 않을까 싶네요.

이것과는 논외로 프로젝트에 린팅 설정 파일을 두지 않고, 디폴트 설정만 사용하는 케이스가 얼마나 될지 궁금하기는 해요. 
또한 제가 지향하는 바는 로컬에서 되도록이면 푸시 이전에 정적 검사를 한 번 하고 가자는 쪽이거든요. 그래서 훅을 만들어 둔 것이구요. CI에 추가하는 것은 혹시나 모를 일을 위한 최후의 보루랄까요...?

2022-02-09 02:00 UTC, proost commented on golangci-templates/default.golangci.yml
> +    - internal/service/featuresvc/graph/resolver
@jinwoo1225 

프로젝트의 구성 때문에 skip-dirs를 변경했어요. 가이드에 나온 것을 템플릿으로 사용하셔야 합니다.

2022-02-09 02:00 UTC, jinwoo1225 commented
사용방식을 이런식으로 생각해두었어요!

CASE 1 : 팀 내에서 Team Lint Config를 설정한다.
--> daangn/.github/golangci-templates/default.golangci.yml 같이 공용 저장소를 가르키는 것이 아닌 어떠한 internal 저장소를 사용하면 될것 같아요. EX) `daangn/XXX-TEAM-CONFIG` or `daangn/lint-config/tree/XXX-TEAM`
--> action에 주석을 달아서 다른 레포(Lint Config 저장소)를 사용하던가 아니면 실행레포 내의 golangci.yml을 사용하면 된다는 info를 주면 될것같아요.

CASE 2 : 고수준의 Linter는 사용하고 싶지만, 설정을 어떻게 할지 고민이다.
--> 작성시에 이 케이스에 상황을 맞춰두고 생각했어요. @proost 가 [현재 미디엄 글을 작성](https://daangn.slack.com/archives/C01J0NW1NAW/p1644326196800839)(관련 스레드)하고 계신데 Config파일을 공유할 방법이 적어서 제가 제시한 방법이예요!
--> 설정파일 옵션들을 읽다보니 `TL; DR` 모멘트가 몇번 와버려서, 실제 사용자도 커스텀한 사용을 포기할것 같다는 생각이 들었어요.

2022-02-09 02:01 UTC, jinwoo1225 commented
@proost daangn/lint-config 레포를 생성하는건 어떠세용? ㅎㅎ

2022-02-09 02:06 UTC, jinwoo1225 commented on golangci-templates/default.golangci.yml
> +    - internal/service/featuresvc/graph/resolver
앗 그러네요;;;

2022-02-09 02:09 UTC, jinwoo1225 commented on golangci-templates/default.golangci.yml
> +    - internal/service/featuresvc/graph/resolver
fix on d6f60f8

2022-02-09 02:28 UTC, isbang commented
git-checkout 이 아니라 curl 혹은 wget 으로 default lint 파일을 받아오게 액션을 작성하는 것도 방법일 듯 해요. 그럼 lint config를 위한 레포를 만들지 않아도 되니 관리에도 도움될 수 있구요

2022-02-09 03:16 UTC, mingrammer commented
@proost 의 의견대로 어차피 로컬에서도 linter를 돌릴 필요가 있기 때문에 golangci lint 설정 파일은 각 프로젝트 레포에 포함이 되어야할 것 같아요. 따라서, 공용 lint action을 만든다면 golangci lint 설정 파일은 이미 있다고 가정한 상태에서 lint workflow만 제공해주면 되지 않을까 합니다. 설정 파일은 @isbang 의견처럼 이 레포와는 무관한 다른곳 (별도 레포가 접근성이 제일 좋을듯)에 저장해두고 해당 레포의 리드미에서 default 설정 파일 사용 방법만 가이드 해주면 충분하지 않을까합니다.

- lint-config 레포에 `.golangci.yml`을 루트 디렉터리에 올려둠.
- .github 레포에는 lint를 수행하는 워크플로우만 정의해둠. (공용)
- lint-config 레포의 README에는 `golnagci.yml`을 다운로드받는 가이드라인과 함께 (@isbang 의 의견대로 curl이나 wget으로 로컬로 가져오는 명령어를 제공해주면 될듯)
- golangci lint를 수행하는 커스텀 action이 있다고 언급해줌.

2022-02-09 04:16 UTC, jinwoo1225 commented
@mingrammer 와 @isbang 의 의견에 많이 공감이 됩니당!!
.github 레포의 용도와 lint config와 겹치는 용도가 아닌것 같기도 해요.
점심먹고 lint-config 레포 만들어볼께용!

2022-02-09 09:38 UTC, isbang commented on workflow-templates/golangci-lint-action.yml
> +            mv default.golangci.yml ${{ env.CONFIG_PATH }}
wget 할 때 한번에 `${{ env.CONFIG_PATH }}`로 저장할 수 있게 하면 더 좋을 것 같아요

2022-02-09 09:38 UTC, isbang commented on workflow-templates/golangci-lint-action.yml
> +  DEFAULT_CONFIG_URL: https://raw.githubusercontent.com/daangn/lint-config/main/golangci-lint/default.golangci.yml
요거를 env 로 빼둔 이유가 있을까요..?

2022-02-10 01:44 UTC, jinwoo1225 commented on workflow-templates/golangci-lint-action.yml
> +            mv default.golangci.yml ${{ env.CONFIG_PATH }}
`wget -O ${{ env.CONFIG_PATH }} ${{ DEFAULT_CONFIG_URL }}` 로 한방에 수정할수 있게 변경할게요~~!

2022-02-10 02:01 UTC, jinwoo1225 commented on workflow-templates/golangci-lint-action.yml
> +  DEFAULT_CONFIG_URL: https://raw.githubusercontent.com/daangn/lint-config/main/golangci-lint/default.golangci.yml
템플릿으로 workflow를 등록했지만, lint config를 등록하지 않은 경우도 있을것이라 생각해서 fallback URL처럼 구성했어요!
하지만 fallback URL도 수정하고 싶을수 있다고 판단이 되어서 환경변수로 두었어요 😎

2022-02-10 02:03 UTC, isbang commented on workflow-templates/golangci-lint-action.yml
> +  DEFAULT_CONFIG_URL: https://raw.githubusercontent.com/daangn/lint-config/main/golangci-lint/default.golangci.yml
아하 좋은 방향이네요 ㅎㅎ

2022-02-10 02:06 UTC, jinwoo1225 commented on workflow-templates/golangci-lint-action.yml
> +            mv default.golangci.yml ${{ env.CONFIG_PATH }}
69a2c52 에서 수정했어요~!

2022-02-10 02:10 UTC, jinwoo1225 commented on workflow-templates/golangci-lint-action.properties.json
> +
공백이 들어갔네요;;; 감사합니당~~!

2022-02-10 02:57 UTC, isbang approved these changes
GTG~

2022-02-10 03:25 UTC, proost approved these changes
수고하셨습니다. 가즈아~

2022-02-10 03:26 UTC, merged